### PR TITLE
Update to use correct LoggerSilencer in ActiveSupport 6

### PR DESCRIPTION
**Pull request by hasghari**
I don't know what the policy of this gem is regarding supporting older ruby versions but given that ruby has officially dropped support for 2.3, I've removed the unsupported versions from the Travis CI build.

### CODE REVIEW

**Comment by schneems** [comment]
You should probably not be using this gem with Rails 6. Rails generates files config that you can use to output logs to stdout with an env var now. I would recommend using that config.

**Comment by hasghari** [comment]
> You should probably not be using this gem with Rails 6. Rails generates files config that you can use to output logs to stdout with an env var now. I would recommend using that config.

Thanks.

**Comment by hasghari** [comment]
@schneems This gem doesn't work as expected in Rails 6 because Rails will always override the logger level and set it to `config.log_level`, regardless of whether we have set up a custom logger. 
https://github.com/rails/rails/blob/ee10e05af27facf42b1c49f8aaa0463d3af6989c/railties/lib/rails/application/bootstrap.rb#L53

**Comment by hasghari** [comment]
In case any one else runs into this for Rails 6, this is how I updated my `config/application.rb` to replace this gem:

```ruby
config.log_level = ENV.fetch('LOG_LEVEL', 'INFO').downcase

if ENV['RAILS_LOG_TO_STDOUT'].present?
  logger           = ActiveSupport::Logger.new(STDOUT)
  logger.level     = ActiveSupport::Logger.const_get(config.log_level.to_s.upcase)
  config.logger    = ActiveSupport::TaggedLogging.new(logger)
end
```

**Pull request closed without merging**
