### PR TITLE
Include Rails 4 logger silence module

### LINKED ISSUE #14: Rails logger silence is not available
We've hit an issue in production trying to use the Rails silence method on the logger:

```ruby
Rails.logger.silence { do_work }
```

This works fine with the [normal Rails logger because it includes the `LoggerSilence` module](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/logger.rb#L7), which provides [the `silence` method](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/logger_silence.rb#L12).

However, the heroku logger provided by this gem does not, which means the `silence` call ends up being the one available through the [Kernel extension that Rails adds](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/core_ext/kernel/reporting.rb#L108) (which is deprecated btw), and turns into an `ArgumentError`:

```ruby
#<ArgumentError: wrong number of arguments (0 for 1)>.

...gems/activesupport-4.2.1/lib/active_support/core_ext/kernel/reporting.rb:88:in `capture'
```

For now I've fixed this locally by including the `LoggerSilence` into the logger's singleton class when activating the stdout logging (since [it needs to be included](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/logger_silence.rb#L6) to have everything properly set up), and I'm wondering if this is something we can fix up in the gem itself, either by doing the same include:

```ruby
logger.singleton_class.include(LoggerSilence) if defined?(LoggerSilence)
```

Or by having a specific logger class for the gem, like: 

```ruby
  class StdoutLogger < ::Logger
    include ::LoggerSilence if defined?(::LoggerSilence)
  end
```

I think I prefer the second approach. Thoughts?

### PR DESCRIPTION
**Pull request by carlosantoniodasilva**
Fixes #14, please read there for more context.

I've also updated the appraisals to add Rails 4.1/4.2 and Ruby 2.1/2.2 - but excluded those with older versions of Rails from the travis build - they are likely to fail anyway.

Let me know if there's anything that needs improving.

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
Ping @schneems :)

**Comment by schneems** [comment]
Yikes, sorry. Somehow this fell off my radar. Thanks :heart:

**Comment by carlosantoniodasilva** [comment]
Thanks! :green_heart::yellow_heart::heart::blue_heart::purple_heart:

**Comment by carlosantoniodasilva** [comment]
@schneems any possibility of getting this released? I want to :fire: my monkey-patch here :smile:

**Comment by schneems** [comment]
v0.0.4 is out

**Comment by carlosantoniodasilva** [comment]
:green_heart::yellow_heart::heart::blue_heart::purple_heart:

**Pull request merged**
