### PR TITLE
Support custom log formatter

### PR DESCRIPTION
**Pull request by sevos**
Should solve #16

### CODE REVIEW

**Comment by schneems** [comment]
I don't think logger has a `formatter` accessor http://ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html

**Comment by sevos** [comment]
Apparently it's not present in the documentation!

```
$ pry                                                                                                  rvm:ruby-2.2.2
[1] pry(main)> require 'logger'
=> true
[2] pry(main)> l = Logger.new($stdout)
=> #<Logger:0x007fa2dd8d7ca0
 @default_formatter=#<Logger::Formatter:0x007fa2dd8d7c78 @datetime_format=nil>,
 @formatter=nil,
 @level=0,
 @logdev=
  #<Logger::LogDevice:0x007fa2dd8d7c00
   @dev=#<IO:<STDOUT>>,
   @filename=nil,
   @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007fa2dd8d7bb0 @mon_count=0, @mon_mutex=#<Mutex:0x007fa2dd8d7b60>, @mon_owner=nil>,
   @shift_age=nil,
   @shift_size=nil>,
 @progname=nil>
[3] pry(main)> cd l
[4] pry(#<Logger>):1> ls
Logger#methods:
  <<   close            datetime_format=  debug?  error?  fatal?     formatter=  info?  level=  progname   sev_threshold   unknown  warn?
  add  datetime_format  debug             error   fatal   formatter  info        level  log     progname=  sev_threshold=  warn
self.methods: __pry__
instance variables: @default_formatter  @formatter  @level  @logdev  @progname
locals: _  __  _dir_  _ex_  _file_  _in_  _out_  _pry_
```

Rails uses it, so it must be there. Please note I ran it without Rails' environment loaded

**Comment by schneems** [comment]
Tests are failing

```
/home/travis/build/heroku/rails_stdout_logging/test/test_helper.rb:5: warning: already initialized constant STDOUT
/home/travis/.rvm/gems/ruby-2.0.0-p647-clang/gems/railties-3.0.20/lib/rails/railtie/configuration.rb:77:in `method_missing': undefined method `log_formatter' for #<Rails::Application::Configuration:0x000000045d8bb8> (NoMethodError)
```

**Comment by schneems** [comment]
Ping, can you handle the failing test case, it looks like that method isn't always available. You could use a `try()`

**Comment by nruth** [comment]
Does this take into account the stuff I said about the rails boot order in #16 or was I off-the-mark with all that? I haven't had opportunity to reverse-engineer Rails logging yet. I'd be great if this does fix everything, as it seems pretty simple.

**Pull request closed without merging**
